name: hello-world
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # greet – произвольно выбранное имя задания
  # их может быть больше одного
  greet:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен, выполняет какую-то задачу
      # checkout – клонирует репозиторий
      - uses: actions/checkout@v3
      # run – произвольная bash-команда
      - run: make say-hello
